### ISSUE TITLE
crf token issue

### ISSUE THREAD

**Issue by atta1234** [amrnn90/breeze-nuxt#11]
"message": "CSRF token mismatch.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\HttpException",
    "file": "D:\\xampp\\htdocs\\example-app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php",
    "line": 428,
    "trace": [
        {
            "file": "D:\\xampp\\htdocs\\example-app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php",
            "line": 399,

**Comment by amrnn90** [comment]
You seem to be using a custom domain name for local development instead of just `localhost`, in that case check [this comment](https://github.com/amrnn90/breeze-nuxt/issues/10#issuecomment-1554885062) and see if it solves your issue.
