### ISSUE TITLE
Fresh install, upgrade nuxt to latest, get infinite loops on /register and /forgot-password

### ISSUE THREAD

**Issue by matthiastjong** [amrnn90/breeze-nuxt#12]
All routes are working properly, but when trying to execute a `/register` or `/forgot-password` action, I get thousands of warnings per second and the browser crashes:

<img width="1283" alt="Screenshot 2023-07-17 at 21 00 18" src="https://github.com/amrnn90/breeze-nuxt/assets/94455356/e3844705-d129-4071-8ca0-92636412604d">

When I try to login again, the new user is created, so that process runs fine.

**Comment by amrnn90** [comment]
Unable to reproduce, can you show what errors (not warnings) are you getting? the errors tab in your screenshot indicates you have 2 errors.
Also are you getting any errors in the terminal where you run the nuxt server?

**Comment by matthiastjong** [comment]
So I rebuilt the Laravel set-up (which was also fresh) and the errors disappeared. Unfortunately I cannot reproduce it also, but happy that it works now.
