### ISSUE TITLE
Redirecting to Login Page on Refresh

### ISSUE THREAD

**Issue by luistrcastro** [amrnn90/breeze-nuxt#17]
Hey man, thank you for putting some time into this repo; it's incredible.

I'm using the verified middleware in my pages in Nuxt, except in login, of course. But when I refresh the page, I'm redirected to the login page and then back to home. Any idea of why this is happening?

Do you want me to provide any snippets from my code?

Thank you for your time

**Comment by amrnn90** [comment]
Hi, are you getting any errors in your browser's console? What about the terminal where you run Nuxt's dev server, any errors there?

**Comment by luistrcastro** [comment]
Hi, sorry for the late response. I'm using your library on a side project which I work on once a month.

I'm not getting any errors on the terminal. In the browser's console, I get this warning 

![image](https://github.com/amrnn90/breeze-nuxt/assets/64997284/0d9a01fb-e9aa-4564-961a-e1a9c8a13c4c)
