### ISSUE TITLE
Error 500 A composable that requires access to the nuxt instance....

### ISSUE THREAD

**Issue by kohlzz** [amrnn90/breeze-nuxt#20]
Hello,

Since recently none working due error message;

"[nuxt] [request error] [unhandled] [500] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function." Any idea? I did this on a fresh installation.

Regards,
Kohlzz

**Comment by amrnn90** [comment]
Hi, I am unable to reproduce this. Can you show me the output of this command `npx nuxi info`?

**Comment by kohlzz** [comment]
This is the output of that command;


- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@8.13.1
- Builder:          -
- User Config:      devtools, runtimeConfig, imports, modules, app
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.1
- Build Modules:    -

**Comment by amrnn90** [comment]
Have you removed this from `nuxt.config.ts` file?
```ts
{
  experimental: {
    asyncContext: true,
  }
}
```

**Comment by kohlzz** [comment]
That was indeed the case, I removed it from the config somehow. Silly i didn't notice it but thank you, this worked :)

**Comment by amrnn90** [comment]
Glad it worked out for you.

**Comment by kohlzz** [comment]
Hey, sorry i was too fast. It seems to work ony under ssr:false


Verzonden vanuit Mail voor Windows

Van: Amr Noman
Verzonden: zaterdag 25 november 2023 18:52
Aan: amrnn90/breeze-nuxt
CC: kohlzz; Author
Onderwerp: Re: [amrnn90/breeze-nuxt] Error 500 A composable that requires accessto the nuxt instance.... (Issue #20)

Glad it worked out for you.
