### ISSUE TITLE
npm run build error  [nuxt] [request error] [unhandled] [500] useEvent is not defined

### ISSUE THREAD

**Issue by mydidefix** [amrnn90/breeze-nuxt#25]
A really great starter kit, but unfortunately I get the error
when executing 
npm run build
node .output/server/index.mjs

Listening on http://[::]:3000
[nuxt] [request error] [unhandled] [500] useEvent is not defined

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      modules, runtimeConfig, imports, experimental
- Runtime Modules:  @nuxtjs/tailwindcss@6.10.0
- Build Modules:    -

Compiling also does not work when I reload the system.
npm run dev works fine.

Thanks for the help.

**Comment by amrnn90** [comment]
I believe this is the same as #23 and should have already been fixed, is your cloned repo up to date?

**Comment by mydidefix** [comment]
Thank you very much for your help.
Can you help me with this? I will pay you for it too.
With kind regards
Dieter

**Comment by amrnn90** [comment]
Like I said, this issue was already fixed a while ago in [this commit](https://github.com/amrnn90/breeze-nuxt/commit/987d4f316068d0203a0a534235401909d7b14afc). Is your local repo up to date?

**Comment by mydidefix** [comment]
Unfortunately I don't know how to clone the update.
Can you please help me with this would be super important.

**Comment by amrnn90** [comment]
Just run: `git pull origin master`

**Comment by mydidefix** [comment]
**That was the solution.** Thank you very much for your help.
Great project and very helpful.
