### ISSUE TITLE
Only works on same domain

### ISSUE THREAD

**Issue by timothymarois** [amrnn90/breeze-nuxt#6]
With CSRF and relying on laravel cookies, it appears this can not be opened up to cross-domains. The best setup is to have API and UI on their own isolated domain names. a root and a subdomain. Unless I'm missing something, it doesn't appear that this will work.

**Comment by amrnn90** [comment]
Hi @timothymarois ,
This should work as long as your API and frontend share the same top-level domain.
From the [Laravel Sanctum docs](https://laravel.com/docs/9.x/sanctum#spa-authentication):
> In order to authenticate, your SPA and API must share the same top-level domain. However, they may be placed on different subdomains.

You will likely need to add this to your Laravel's `.env` file to avoid authentication issues: 
```
SESSION_DOMAIN=.yourdomain.com
```
Pay attention to include that dot prefix.

Hope this helps.
