### ISSUE TITLE
Blob via submitRequest util

### ISSUE THREAD

**Issue by hiddenLadder** [amrnn90/breeze-nuxt#8]
how do i send a blob image using submitRequest? I tried to set Content-Type header as multipart/form-data but it didnt work

**Comment by misbahansori** [comment]
You need to use form data for that case
```
const formData = new FormData();
formData.append("_method", "PUT");

formData.append("avatar", profileForm.value.avatar);

const data = await $larafetch(`/api/profile`, {
  method: "POST",
  body: formData,
});
```

**Comment by misbahansori** [comment]
Do you want to submit the form as POST or PUT request?

**Comment by hiddenLadder** [comment]
i want to submit form as PUT request with image

**Comment by hiddenLadder** [comment]
`
const form = reactive({
    _method: 'PUT',
    first_name: account.value.first_name,
    surname: account.value.surname,
    patronymic: account.value.patronymic,
    graduation_year: account.value.graduation_year,
    country: account.value.country,
    city: account.value.city,
    job: account.value.job,
    comment: account.value.comment,
    avatar_url: null as Blob,
    faculty_id: account.value.faculty_id,
    position_x: account.value.position_x,
    position_y: account.value.position_y,
});
// ....

 const formData = new FormData();
    for (let key in form) {
        formData.append(key, form[key]);
    }
    submitRequest(
        $larafetch(`/account/${account.value.id}`, {
            headers: {
                "Content-Type": "multipart/form-data",
            },
            method: "POST",
            body: formData,
        }))
`

**Comment by hiddenLadder** [comment]
```js
const form = reactive({
_method: 'PUT',
first_name: account.value.first_name,
surname: account.value.surname,
patronymic: account.value.patronymic,
graduation_year: account.value.graduation_year,
country: account.value.country,
city: account.value.city,
job: account.value.job,
comment: account.value.comment,
avatar_url: null as Blob,
faculty_id: account.value.faculty_id,
position_x: account.value.position_x,
position_y: account.value.position_y,
});
// ....

const formData = new FormData();
for (let key in form) {
formData.append(key, form[key]);
}
submitRequest(
$larafetch(/account/${account.value.id}, {
headers: {
"Content-Type": "multipart/form-data",
},
method: "POST",
body: formData,
}))
```

**Comment by misbahansori** [comment]
I don't think you need the "Content-Type": "multipart/form-data" headers

**Comment by hiddenLadder** [comment]
doesnt work either

**Comment by amrnn90** [comment]
Can you please pull the latest commit and see if your issue is solved?

**Comment by hiddenLadder** [comment]
@amrnn90 yeah now it works thank you
